version: '3.7'
services:
  shell:
    build:
      context: ./shell
    ports:
      - "3000:3000"
    networks:
      - microservices-network

  track:
    build:
      context: ./track
    ports:
      - "5002:5002"
    networks:
      - microservices-network

  authorization:
    build:
      context: ./authorization
    ports:
      - "5001:5001"
    networks:
      - microservices-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - shell
      - track
      - authorization
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true
    name: react-webpack-router-mfs_microservices-network
